export async function fetchCityVolunteers() {
  return [
    {
      title: "City of Toronto Volunteer Programs",
      organization: "City of Toronto",
      duration: "Varies",
      introduction: "Volunteer with the City of Toronto.",
      summary: "City-run volunteer programs across Toronto.",
      bestFor: ["community", "leadership"],
      requirements: ["Age 14+"],
      languages: ["English"],
      link: "https://www.toronto.ca/explore-enjoy/recreation/volunteer/",
      source_type: "official",
      source_name: "city_of_toronto",
    },

    {
      title: "Toronto Food Bank Volunteers",
      organization: "Daily Bread Food Bank",
      duration: "Flexible",
      introduction: "Help fight hunger in Toronto.",
      summary: "Sorting food, packing hampers, helping community.",
      bestFor: ["community", "service"],
      requirements: ["Age 14+", "Commitment preferred"],
      languages: ["English"],
      link: "https://www.dailybread.ca/volunteer/",
      source_type: "official",
      source_name: "food_bank",
    },

    {
      title: "Hospital Volunteer Program",
      organization: "Sunnybrook Hospital",
      duration: "3-6 months",
      introduction: "Volunteer in healthcare environment.",
      summary: "Assist patients, front desk, hospital services.",
      bestFor: ["health", "psychology"],
      requirements: ["Age 16+"],
      languages: ["English"],
      link: "https://sunnybrook.ca/content/?page=volunteer",
      source_type: "official",
      source_name: "hospital",
    },

    {
      title: "Youth Mentorship Volunteer",
      organization: "Big Brothers Big Sisters",
      duration: "Ongoing",
      introduction: "Mentor younger students.",
      summary: "Build relationships and support youth growth.",
      bestFor: ["education", "leadership"],
      requirements: ["Background check"],
      languages: ["English"],
      link: "https://bigbrothersbigsisters.ca/toronto/volunteer/",
      source_type: "official",
      source_name: "mentorship",
    },

    {
      title: "Community Event Volunteer",
      organization: "Toronto Festivals",
      duration: "Short-term",
      introduction: "Help at local events and festivals.",
      summary: "Event setup, guest support, logistics.",
      bestFor: ["events", "social"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.toronto.ca/explore-enjoy/festivals-events/",
      source_type: "official",
      source_name: "events",
    },
  ];
}