export async function fetchMegaVolunteers() {
  return [
    {
      title: "YMCA Youth Volunteer",
      organization: "YMCA Toronto",
      duration: "Flexible",
      introduction: "Support youth and recreation programs.",
      summary: "Great for leadership and teamwork experience.",
      bestFor: ["leadership", "community"],
      requirements: ["Age 14+"],
      languages: ["English"],
      link: "https://ymcagta.org/",
    },
    {
      title: "Food Sorting Volunteer",
      organization: "Daily Bread Food Bank",
      duration: "Flexible",
      introduction: "Help organize food donations.",
      summary: "Community service helping families in need.",
      bestFor: ["community", "service"],
      requirements: ["Age 14+"],
      languages: ["English"],
      link: "https://www.dailybread.ca/",
    },
    {
      title: "Library Teen Volunteer",
      organization: "Toronto Public Library",
      duration: "Seasonal",
      introduction: "Assist library programs and events.",
      summary: "Ideal for education and communication skills.",
      bestFor: ["education"],
      requirements: ["Age 14+"],
      languages: ["English"],
      link: "https://www.torontopubliclibrary.ca/",
    },
    {
      title: "Hospital Front Desk Volunteer",
      organization: "Sunnybrook Hospital",
      duration: "3 months",
      introduction: "Welcome and guide visitors.",
      summary: "Great exposure to healthcare environment.",
      bestFor: ["health"],
      requirements: ["Age 16+"],
      languages: ["English"],
      link: "https://sunnybrook.ca/",
    },
    {
      title: "Zoo Event Volunteer",
      organization: "Toronto Zoo",
      duration: "Weekend",
      introduction: "Support family events and activities.",
      summary: "Great for animal lovers and events.",
      bestFor: ["animals", "events"],
      requirements: ["Age 14+"],
      languages: ["English"],
      link: "https://www.torontozoo.com/",
    },
    {
      title: "Museum Guide Assistant",
      organization: "ROM",
      duration: "Flexible",
      introduction: "Help visitors in museum exhibits.",
      summary: "Strong for arts and history interests.",
      bestFor: ["history", "arts"],
      requirements: ["Age 15+"],
      languages: ["English"],
      link: "https://www.rom.on.ca/",
    },
    {
      title: "Festival Crew Volunteer",
      organization: "TIFF",
      duration: "Short-term",
      introduction: "Support Toronto film festival events.",
      summary: "Perfect for media and networking.",
      bestFor: ["media", "events"],
      requirements: ["Age 16+"],
      languages: ["English"],
      link: "https://tiff.net/",
    },
    {
      title: "Animal Shelter Assistant",
      organization: "Toronto Humane Society",
      duration: "Flexible",
      introduction: "Support shelter care teams.",
      summary: "Good for pre-vet and compassion work.",
      bestFor: ["animals", "health"],
      requirements: ["Age 16+"],
      languages: ["English"],
      link: "https://www.torontohumanesociety.com/",
    },
    {
      title: "Community Garden Volunteer",
      organization: "Green Toronto",
      duration: "Weekend",
      introduction: "Help maintain urban gardens.",
      summary: "Environmental leadership experience.",
      bestFor: ["environment"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.toronto.ca/",
    },
    {
      title: "Senior Home Companion",
      organization: "Toronto Seniors Centre",
      duration: "Flexible",
      introduction: "Spend time with seniors.",
      summary: "Strong for healthcare and empathy.",
      bestFor: ["health", "community"],
      requirements: ["Age 15+"],
      languages: ["English"],
      link: "https://www.toronto.ca/",
    },

    {
      title: "Tutor Volunteer",
      organization: "Community Learning Hub",
      duration: "Weekly",
      introduction: "Tutor younger students.",
      summary: "Great for teaching and patience.",
      bestFor: ["education"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.tdsb.on.ca/",
    },
    {
      title: "Fundraising Volunteer",
      organization: "Red Cross Toronto",
      duration: "Flexible",
      introduction: "Assist fundraising campaigns.",
      summary: "Business and nonprofit experience.",
      bestFor: ["business", "leadership"],
      requirements: ["Age 14+"],
      languages: ["English"],
      link: "https://www.redcross.ca/",
    },
    {
      title: "Park Cleanup Volunteer",
      organization: "City of Toronto",
      duration: "Weekend",
      introduction: "Join community cleanup days.",
      summary: "Environmental service work.",
      bestFor: ["environment"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.toronto.ca/",
    },
    {
      title: "Youth Mentor",
      organization: "Big Brothers Big Sisters",
      duration: "Ongoing",
      introduction: "Mentor younger students.",
      summary: "Leadership and communication growth.",
      bestFor: ["leadership", "education"],
      requirements: ["Screening"],
      languages: ["English"],
      link: "https://bigbrothersbigsisters.ca/",
    },
    {
      title: "Hospital Gift Shop Helper",
      organization: "North York General",
      duration: "Flexible",
      introduction: "Support gift shop operations.",
      summary: "Customer service in hospital setting.",
      bestFor: ["business", "health"],
      requirements: ["Age 16+"],
      languages: ["English"],
      link: "https://www.nygh.on.ca/",
    },
    {
      title: "Food Delivery Volunteer",
      organization: "Second Harvest",
      duration: "Flexible",
      introduction: "Deliver rescued food.",
      summary: "Community impact and logistics.",
      bestFor: ["community"],
      requirements: ["Age 16+"],
      languages: ["English"],
      link: "https://secondharvest.ca/",
    },
    {
      title: "Event Registration Volunteer",
      organization: "Toronto Marathon",
      duration: "One-day",
      introduction: "Help race participants register.",
      summary: "Sports event experience.",
      bestFor: ["sports", "events"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.torontomarathon.com/",
    },
    {
      title: "Community Outreach Volunteer",
      organization: "Volunteer Toronto",
      duration: "Flexible",
      introduction: "Support community outreach events.",
      summary: "Networking and service experience.",
      bestFor: ["community"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.volunteertoronto.ca/",
    },
    {
      title: "Reception Volunteer",
      organization: "CAMH",
      duration: "3 months",
      introduction: "Assist visitors and staff.",
      summary: "Mental health environment exposure.",
      bestFor: ["psychology", "health"],
      requirements: ["Age 16+"],
      languages: ["English"],
      link: "https://www.camh.ca/",
    },
    {
      title: "Charity Store Volunteer",
      organization: "Salvation Army",
      duration: "Flexible",
      introduction: "Support donation centre.",
      summary: "Retail + service experience.",
      bestFor: ["business", "community"],
      requirements: ["Age 14+"],
      languages: ["English"],
      link: "https://salvationarmy.ca/",
    },

    {
      title: "Coding Mentor",
      organization: "Youth Tech Lab",
      duration: "Weekly",
      introduction: "Teach coding basics to youth.",
      summary: "Excellent for CS applicants.",
      bestFor: ["stem", "education"],
      requirements: ["Coding skills"],
      languages: ["English"],
      link: "https://www.canada.ca/",
    },
    {
      title: "Science Camp Volunteer",
      organization: "STEM Toronto",
      duration: "Summer",
      introduction: "Help run STEM camps.",
      summary: "Perfect for engineering students.",
      bestFor: ["stem"],
      requirements: ["Age 15+"],
      languages: ["English"],
      link: "https://www.toronto.ca/",
    },
    {
      title: "Translation Volunteer",
      organization: "Community Centre",
      duration: "Flexible",
      introduction: "Translate documents for families.",
      summary: "Great for bilingual students.",
      bestFor: ["languages", "community"],
      requirements: ["2 languages"],
      languages: ["English", "Chinese"],
      link: "https://www.toronto.ca/",
    },
    {
      title: "Museum Events Volunteer",
      organization: "AGO",
      duration: "Weekend",
      introduction: "Assist public art events.",
      summary: "Creative arts experience.",
      bestFor: ["arts"],
      requirements: ["Age 15+"],
      languages: ["English"],
      link: "https://ago.ca/",
    },
    {
      title: "School Fair Volunteer",
      organization: "TDSB",
      duration: "One-day",
      introduction: "Support school community events.",
      summary: "Easy hours for students.",
      bestFor: ["community"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.tdsb.on.ca/",
    },
    {
      title: "Sports Camp Assistant",
      organization: "Toronto Recreation",
      duration: "Summer",
      introduction: "Help children sports camps.",
      summary: "Great for kinesiology interests.",
      bestFor: ["sports", "health"],
      requirements: ["Age 15+"],
      languages: ["English"],
      link: "https://www.toronto.ca/",
    },
    {
      title: "Mental Health Support Volunteer",
      organization: "Youth Wellness Toronto",
      duration: "Flexible",
      introduction: "Support youth wellbeing programs.",
      summary: "Strong for psychology pathway.",
      bestFor: ["psychology"],
      requirements: ["Training"],
      languages: ["English"],
      link: "https://www.camh.ca/",
    },
    {
      title: "Nonprofit Social Media Volunteer",
      organization: "Toronto Charity Hub",
      duration: "Remote",
      introduction: "Manage social media posts.",
      summary: "Perfect for business/media students.",
      bestFor: ["business", "media"],
      requirements: ["Basic design skills"],
      languages: ["English"],
      link: "https://www.canadahelps.org/",
    },
    {
      title: "Festival Photographer",
      organization: "Toronto Events",
      duration: "Weekend",
      introduction: "Capture event photos.",
      summary: "Portfolio building opportunity.",
      bestFor: ["media", "arts"],
      requirements: ["Camera helpful"],
      languages: ["English"],
      link: "https://www.toronto.ca/",
    },
    {
      title: "Community Hotline Volunteer",
      organization: "Toronto Help Line",
      duration: "Flexible",
      introduction: "Assist hotline admin tasks.",
      summary: "Strong communication experience.",
      bestFor: ["community", "health"],
      requirements: ["Training"],
      languages: ["English"],
      link: "https://www.toronto.ca/",
    },
  ];
}