export async function fetchCityVolunteers() {
  return [
    {
      title: "City of Toronto Volunteer Programs",
      organization: "City of Toronto",
      duration: "Varies",
      introduction: "Volunteer with the City of Toronto.",
      summary: "City-run volunteer programs across Toronto.",
      bestFor: ["community", "leadership"],
      requirements: ["Age 14+"],
      languages: ["English"],
      link: "https://www.toronto.ca/explore-enjoy/recreation/volunteer/",
    },

    {
      title: "Food Bank Volunteer",
      organization: "Daily Bread Food Bank",
      duration: "Flexible",
      introduction: "Help fight hunger.",
      summary: "Sorting food and helping distribution.",
      bestFor: ["community"],
      requirements: ["Age 14+"],
      languages: ["English"],
      link: "https://www.dailybread.ca/volunteer/",
    },

    {
      title: "Hospital Volunteer",
      organization: "Sunnybrook Hospital",
      duration: "3-6 months",
      introduction: "Volunteer in healthcare.",
      summary: "Assist patients and staff.",
      bestFor: ["health"],
      requirements: ["Age 16+"],
      languages: ["English"],
      link: "https://sunnybrook.ca/content/?page=volunteer",
    },

    {
      title: "Youth Mentor",
      organization: "Big Brothers Big Sisters",
      duration: "Ongoing",
      introduction: "Mentor youth.",
      summary: "Support younger students.",
      bestFor: ["education"],
      requirements: ["Background check"],
      languages: ["English"],
      link: "https://bigbrothersbigsisters.ca/toronto/volunteer/",
    },

    {
      title: "Festival Volunteer",
      organization: "Toronto Events",
      duration: "Short-term",
      introduction: "Help at events.",
      summary: "Event setup and support.",
      bestFor: ["social"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.toronto.ca/explore-enjoy/festivals-events/",
    },

    {
      title: "Animal Shelter Helper",
      organization: "Toronto Humane Society",
      duration: "Flexible",
      introduction: "Help animals.",
      summary: "Assist shelter operations.",
      bestFor: ["animals"],
      requirements: ["Age 16+"],
      languages: ["English"],
      link: "https://www.torontohumanesociety.com/volunteer/",
    },

    {
      title: "Library Assistant",
      organization: "Community Libraries",
      duration: "Flexible",
      introduction: "Support library work.",
      summary: "Help organize materials.",
      bestFor: ["education"],
      requirements: ["Age 14+"],
      languages: ["English"],
      link: "https://www.torontopubliclibrary.ca/support-us/volunteering/",
    },

    {
      title: "Community Kitchen Volunteer",
      organization: "Local Kitchens",
      duration: "Flexible",
      introduction: "Help prepare meals.",
      summary: "Support community food programs.",
      bestFor: ["community"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.dailybread.ca/volunteer/",
    },

    {
      title: "Environmental Cleanup",
      organization: "Green Toronto",
      duration: "Short-term",
      introduction: "Clean parks and spaces.",
      summary: "Outdoor environmental work.",
      bestFor: ["environment"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.toronto.ca/services-payments/water-environment/environmental-grants-incentives/",
    },

    {
      title: "Senior Home Volunteer",
      organization: "Retirement Homes",
      duration: "Ongoing",
      introduction: "Support seniors.",
      summary: "Spend time and assist residents.",
      bestFor: ["health", "community"],
      requirements: ["Age 15+"],
      languages: ["English"],
      link: "https://www.toronto.ca/community-people/children-parenting/seniors-services/",
    },

    {
      title: "Tutoring Volunteer",
      organization: "Community Education",
      duration: "Flexible",
      introduction: "Help students learn.",
      summary: "Tutor younger students.",
      bestFor: ["education"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.tdsb.on.ca/Community/Community-Services",
    },

    {
      title: "Museum Volunteer",
      organization: "Toronto Museums",
      duration: "Flexible",
      introduction: "Support museum visitors.",
      summary: "Help with exhibits and tours.",
      bestFor: ["history"],
      requirements: ["Age 16+"],
      languages: ["English"],
      link: "https://www.toronto.ca/explore-enjoy/history-art-culture/museums/",
    },

    {
      title: "Sports Event Volunteer",
      organization: "Local Sports Clubs",
      duration: "Short-term",
      introduction: "Assist sports events.",
      summary: "Help organize games.",
      bestFor: ["sports"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.toronto.ca/explore-enjoy/recreation/",
    },

    {
      title: "Charity Fundraising Volunteer",
      organization: "Nonprofit Groups",
      duration: "Flexible",
      introduction: "Help fundraising.",
      summary: "Assist campaigns and events.",
      bestFor: ["business"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.canadahelps.org/en/volunteering/",
    },

    {
      title: "Community Outreach Volunteer",
      organization: "Local NGOs",
      duration: "Ongoing",
      introduction: "Support outreach work.",
      summary: "Help connect with community.",
      bestFor: ["social"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.volunteertoronto.ca/",
    },
  ];
}