export async function fetchExtraVolunteers() {
  return [
    {
      title: "SickKids Family Support Volunteer",
      organization: "SickKids Hospital",
      duration: "3 months",
      introduction: "Support patients and families.",
      summary: "Excellent for pre-med and healthcare pathways.",
      bestFor: ["health"],
      requirements: ["Age 16+"],
      languages: ["English"],
      link: "https://www.sickkids.ca/",
    },
    {
      title: "CAMH Youth Wellness Volunteer",
      organization: "CAMH",
      duration: "Flexible",
      introduction: "Assist mental health youth programs.",
      summary: "Great for psychology and health students.",
      bestFor: ["psychology", "health"],
      requirements: ["Training"],
      languages: ["English"],
      link: "https://www.camh.ca/",
    },
    {
      title: "Startup Event Volunteer",
      organization: "Toronto Startup Hub",
      duration: "Weekend",
      introduction: "Help run startup networking events.",
      summary: "Strong for business and entrepreneurship.",
      bestFor: ["business"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.toronto.ca/",
    },
    {
      title: "Coding Camp Mentor",
      organization: "Youth Tech Toronto",
      duration: "Summer",
      introduction: "Mentor students learning coding.",
      summary: "Perfect for CS students.",
      bestFor: ["stem"],
      requirements: ["Coding skills"],
      languages: ["English"],
      link: "https://www.canada.ca/",
    },
    {
      title: "Science Fair Volunteer",
      organization: "Toronto STEM Network",
      duration: "Short-term",
      introduction: "Assist local science fairs.",
      summary: "Strong STEM extracurricular.",
      bestFor: ["stem"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.toronto.ca/",
    },
    {
      title: "Community Kitchen Assistant",
      organization: "Toronto Community Kitchen",
      duration: "Flexible",
      introduction: "Prepare meals for families.",
      summary: "Meaningful service experience.",
      bestFor: ["community"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.dailybread.ca/",
    },
    {
      title: "Park Tree Planting Volunteer",
      organization: "Green Toronto",
      duration: "Weekend",
      introduction: "Plant trees in Toronto parks.",
      summary: "Environmental leadership opportunity.",
      bestFor: ["environment"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.toronto.ca/",
    },
    {
      title: "Hospital Admin Volunteer",
      organization: "Mount Sinai Hospital",
      duration: "Flexible",
      introduction: "Support front desk operations.",
      summary: "Healthcare + office skills.",
      bestFor: ["health"],
      requirements: ["Age 16+"],
      languages: ["English"],
      link: "https://www.mountsinai.on.ca/",
    },
    {
      title: "Marketing Volunteer",
      organization: "Toronto Charity Hub",
      duration: "Remote",
      introduction: "Help nonprofit marketing.",
      summary: "Excellent for business applicants.",
      bestFor: ["business"],
      requirements: ["Basic Canva helpful"],
      languages: ["English"],
      link: "https://www.canadahelps.org/",
    },
    {
      title: "Robotics Camp Volunteer",
      organization: "STEM Kids Toronto",
      duration: "Summer",
      introduction: "Help robotics camps.",
      summary: "Great for engineering students.",
      bestFor: ["stem"],
      requirements: ["Age 15+"],
      languages: ["English"],
      link: "https://www.toronto.ca/",
    },

    {
      title: "School Orientation Volunteer",
      organization: "TDSB",
      duration: "One-day",
      introduction: "Help welcome new students.",
      summary: "Easy volunteer hours for students.",
      bestFor: ["community"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.tdsb.on.ca/",
    },
    {
      title: "Library Reading Buddy",
      organization: "Toronto Public Library",
      duration: "Weekly",
      introduction: "Read with younger children.",
      summary: "Great for education majors.",
      bestFor: ["education"],
      requirements: ["Age 14+"],
      languages: ["English"],
      link: "https://www.torontopubliclibrary.ca/",
    },
    {
      title: "Senior Recreation Volunteer",
      organization: "Toronto Seniors Centre",
      duration: "Flexible",
      introduction: "Lead games and activities.",
      summary: "Excellent for healthcare pathways.",
      bestFor: ["health", "community"],
      requirements: ["Age 15+"],
      languages: ["English"],
      link: "https://www.toronto.ca/",
    },
    {
      title: "Festival Media Crew",
      organization: "TIFF",
      duration: "Short-term",
      introduction: "Assist festival media operations.",
      summary: "Great for communications students.",
      bestFor: ["media"],
      requirements: ["Age 16+"],
      languages: ["English"],
      link: "https://tiff.net/",
    },
    {
      title: "AGO Youth Volunteer",
      organization: "AGO",
      duration: "Weekend",
      introduction: "Support art events.",
      summary: "Strong for arts students.",
      bestFor: ["arts"],
      requirements: ["Age 15+"],
      languages: ["English"],
      link: "https://ago.ca/",
    },
    {
      title: "Fundraising Campaign Volunteer",
      organization: "Red Cross Toronto",
      duration: "Flexible",
      introduction: "Help donation drives.",
      summary: "Business + nonprofit impact.",
      bestFor: ["business"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.redcross.ca/",
    },
    {
      title: "Animal Care Assistant",
      organization: "Toronto Humane Society",
      duration: "Flexible",
      introduction: "Support shelter staff.",
      summary: "Ideal for pre-vet students.",
      bestFor: ["animals"],
      requirements: ["Age 16+"],
      languages: ["English"],
      link: "https://www.torontohumanesociety.com/",
    },
    {
      title: "Community Hotline Assistant",
      organization: "Toronto Help Centre",
      duration: "Flexible",
      introduction: "Support admin and outreach.",
      summary: "Great communication experience.",
      bestFor: ["community"],
      requirements: ["Training"],
      languages: ["English"],
      link: "https://www.toronto.ca/",
    },
    {
      title: "Youth Sports Volunteer",
      organization: "Toronto Recreation",
      duration: "Weekend",
      introduction: "Help youth sports leagues.",
      summary: "Strong for kinesiology students.",
      bestFor: ["sports"],
      requirements: ["None"],
      languages: ["English"],
      link: "https://www.toronto.ca/",
    },
    {
      title: "Photography Volunteer",
      organization: "Toronto Events",
      duration: "Weekend",
      introduction: "Take photos at local events.",
      summary: "Build portfolio and media skills.",
      bestFor: ["media", "arts"],
      requirements: ["Camera helpful"],
      languages: ["English"],
      link: "https://www.toronto.ca/",
    },
  ];
}